filter:
    paths:
        - src/*
checks:
    php:
        code_rating: true
        duplication: true
build:
    tests:
        override:
            -
                command: 'composer coverage'
                coverage:
                    file: 'build/coverage.clover'
                    format: 'clover'